<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Tagging\GTM\DataLayer\Event\BeginCheckout as BeginCheckoutEvent;
use Tagging\GTM\MageWire\Checkout as CheckoutComponent;

/** @var Template $block */
/** @var BeginCheckoutEvent $beginCheckoutEvent */
/** @var CheckoutComponent $magewire */
$magewire = $block->getData('magewire');
if (false === $magewire->isHyvaCheckoutEnabled()) {
    return;
}

$beginCheckoutEvent = $block->getData('begin_checkout_event');
$beginCheckoutPayload = $beginCheckoutEvent->get();
?>
<div class="hidden">
    <script>
        (function () {
            "use strict";

            window.addEventListener('ga:trigger-event', function (event) {
                googleTagManager2Pusher(event.detail, 'Hyva Checkout');
            }, {passive: true});

            googleTagManager2Pusher(<?= /* @noEscape */ json_encode($beginCheckoutPayload) ?>, 'Hyva Checkout');
        })();
    </script><?php if (isset($hyvaCsp) && $hyvaCsp): ?><?php $hyvaCsp->registerInlineScript() ?><?php endif; ?>
</div>
